version: "3.9"
services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - env/api-service.env
  postgres:
    image: postgres
    env_file:
      - env/postgres.env
    ports:
      - "5432:5432"
