version: "3.9"
services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - env/api-service.env
  postgres:
    image: postgres
    env_file:
      - env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      # https://gist.github.com/onjin/2dd3cc52ef79069de1faa2dfd456c945
      - ./sql/music_genre_tab.sql:/docker-entrypoint-initdb.d/music_genre_tab.sql
