# generated by datamodel-codegen:
#   filename:  title_list.json
#   timestamp: 2021-08-22T07:25:32+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Model(BaseModel):
    status: str
    status_code: int
    genre: str
    titles: List[str]
